### ISSUE TITLE
include videochats via webrtc links

### ISSUE THREAD

**Issue by roth-a** [deltachat/deltachat-core#101] opened 2018-02-05 06:40 UTC
Videochats are an important part of every messenger. Can Delta chat include a video chat button, that opens a webrtc link in the browser?

**Comment by testbird** [comment] 2018-02-05 09:08
Do you have an example how links have to look like?

**Comment by roth-a** [comment] 2018-02-05 09:55
For the beginning delta chat could use a third party provider like:
https://videolink2.me/
But in the long run, this could be hosted on an own server following the webrtc guidelines: https://www.html5rocks.com/en/tutorials/webrtc/basics/

**Comment by Hocceruser** [comment] 2018-02-05 20:10
Related to / duplicate of #44 (?) (although I also think that it would be a very useful & important feature)

**Comment by testbird** [comment] 2018-02-10 11:37
If you would like to implement this, you could probably rely on delta chat messages for the signaling (removing the requirement for a webrtc signaling server) and use a library like simplewebrtc to set up the video streams (alternatives: https://stackoverflow.com/questions/24857637/current-state-of-javascript-webrtc-libraries).

**Comment by testbird** [comment] 2018-02-10 11:40
https://stackoverflow.com/a/29056385

**Comment by testbird** [comment] 2018-02-12 10:04
@r10s Hi, hope your are well and feel completely healthy again.

Maybe you or the general autocrypt folks already thought about a email message format that would fit for p2p session initiation and communication signaling for external apps. Here is a chance to integrate with the new Nextcloud talk:
https://github.com/nextcloud/talk-android/issues/58#issuecomment-364872566

**Comment by testbird** [comment] 2018-02-12 11:00
Ideally there could be a standard "email push" message format. Some day, free operating system platforms could then only need one OS process holding the IMAP server watch connection open, and notifying apps as necessary.

**Comment by r10s** [comment] 2018-02-12 16:45
@testbird thanks, i am well and healthy again :)

thank you for pointing in the direction, i really like the idea of a push message initializing the a/v, however, i have not though much in details about this (an i will not have the time until Delta Chat 1.0 is ready and in Play Store :)

**Comment by testbird** [comment] 2018-02-12 18:32
Good to read. Could you ping other persons (from autocrypt etc.) that might have an interest about replacing google push services with some email (IMAP) push messaging standard?

Derive: Email-Chat messaging standard  -->  Email-Push notification standard
https://stackoverflow.com/questions/20329403/android-push-notification-without-using-gcm


Support for a simple, manual "click-a-link-in-deltachat-to-answer-a-call-with-another-app" (like nextcloud talk) seems like a low hanging fruit for a java dev, so it could get contributed.

**Comment by testbird** [comment] 2018-02-14 08:25
Can you confirm or correct this statement from the [other thread](https://github.com/nextcloud/talk-android/issues/58#issuecomment-365510377):
> The [Telegram-FOSS Android 8.0 issue](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/172) is correct. You cannot guarantee a persistent service, and IMAP push cannot wake the device.

**Comment by testbird** [comment] 2018-02-14 08:42
To me it looks as if you already solved the problems and deltachat-core could already function as a push client library to other apps as well. Areas to improve would be reducing data overhead (message size) after initial handshake and forwarding push notifications to multiple apps (to require only one watching process per device). Your dev perspective would be welcome in the other thread.

**Comment by whippedcream-log** [comment] 2018-03-18 02:46
> wake the device

google must really want your metadata to coerce use of their services

**Comment by r10s** [comment] 2018-03-18 10:25
:)

it's a little bit weird that that there are two issues where discussions take place about a/v calls.
i close this one now in favour to #44 which seems more general to me.

**Closed by r10s** 2018-03-18 10:25 UTC
Labels: duplicate, feature request
