### ISSUE TITLE
Question about the location for the saved messages

### ISSUE THREAD

**Issue by gitkald** [deltachat/deltachat-core#43] opened 2017-08-02 07:09 UTC
_**Wo werden die Nachrichten auf dem IMAP-Server gespeichert?**
Mit Delta Chat versendete Nachrichten werden im Ordner “Chats” gespeichert, ebenso wie Antworten auf mit Delta Chat gesendete Nachrichten (Ausnahme: Googlemail, hier muss bei Bedarf eine Regel im Webinterface angelegt werden)._

On the german help site your can read, that all outgoing DC mails where safed in IMAP folder chat, as well the answers to this mails.

My Problem is, that outgoin messages where safed in the right folder. But answers to this mails, where safed in the normal inbox folder, not in the chat folder.

Is this normal and I misunderstood the meaning of the help or is it a bug?

It does't matter if messages where send by DC chat app or by normal mailclient.

**Comment by csb0730** [comment] 2017-08-03 22:17
In my account (gmx) the same:

- all mails sent from DC:                  "Chats"
- incoming mails from DC:               "Chats"
- incoming mails from other MUA:   "Inbox"

I hope this helps?

Regards

**Comment by gitkald** [comment] 2017-08-04 05:59
Hi csb730,
your answer is like described on the german help side. With my Delta Chat client it shows like this:

- all mails sent from DC: "Chats" (like described on help side)
- incoming mails from DC: "Inbox"
- incoming mails from other MUA: "Inbox"

I've tested it wiht my own provider and a freenet account. On my provider mailbox there's automaticaly created a folder "Chats". On Freenet Account there where no "Chats" folder.

**Comment by Hocceruser** [comment] 2017-08-05 15:14
> (Ausnahme: Googlemail, hier muss bei Bedarf eine Regel im Webinterface angelegt werden).

Maybe Freenet is using something from Gmail in its backend?

**Comment by gitkald** [comment] 2017-08-07 09:12
Hi Hocceruser,
I don't know what freenet uses. This was only a test, because my own domain mailaccount had the same problem. Only my own send messages where stored in folder "Chats", which was created on first time using DC.

**Comment by r10s** [comment] 2017-08-24 10:25
Not sure, if this issue is solved. If so, please close it.

**Comment by gitkald** [comment] 2017-08-24 10:33
No, problem still exists.

The same on Yoga2 tablet with Android 5.0.1 and phone honor 7 with Android 6.0, if this is helps.

**Comment by r10s** [comment] 2017-08-24 10:37
But the core of the issue is the missing "chats" folder on the freenet account?

**Comment by gitkald** [comment] 2017-08-24 10:43
No. I had my own provider. To verify the problem, I tested it with freenet. The same problem.

- all mails sent from DC: "Chats" (like described on help side)
- incoming mails from DC: "Inbox"
- incoming mails from other MUA: "Inbox"

**Comment by gitkald** [comment] 2017-08-28 09:03
Here's a picture, to see what I mean.
I s this behavior so correct? Or must all Messages move to folder chats?
![bilder aneinanderreihen](https://user-images.githubusercontent.com/2179609/29766711-f62aecde-8bdf-11e7-8500-0266ceb2e6da.jpg)

**Comment by r10s** [comment] 2017-09-01 16:31
Thank you very much.

In fact, up to now, it is "by design" that answers to Delta Chat messages from normal MUAs are _not_ moved to the Chats-folder.

Some day in the past, we thought this would be a good idea for whatever reason (maybe not to move some messages from a contact and some not), however, meanwhile, we think that replies from normal MUAs to Delta Chat messages should also be moved to the Chats-folder.

We will implement this, probably with the next update (0.9.5 or more then)

**Comment by gitkald** [comment] 2017-09-11 08:13
But there're normal replies and first time sended messages from a DC client in the inbox too. (see picture above [Chat: verschlüsselte Nachricht])

Only sended messages on my device are moved to folder chat.

**Comment by r10s** [comment] 2017-09-12 17:52
Okay, commit 83c4fcda22b0c62cbd6e978e17306f89cb2aad11 changes the behaviour so that also replies from normal MUA are moved to the Chats-folder.

NB: The messages are moved only when they're _viewed_ in Delta Chat. Up to this moment, they stay in the inbox. This is a desired behaviour to not miss some messages when switching from Delta Chat to a normal MUA for a given moment.

**Closed by r10s** 2017-09-12 17:52 UTC
Labels: being worked on

**Comment by csb0730** [comment] 2017-09-13 07:27
good decision.

cs

Am 12. September 2017 19:52:19 MESZ schrieb "Björn Petersen" <notifications@github.com>:
>Okay, commit 83c4fcda22b0c62cbd6e978e17306f89cb2aad11 changes the
>behaviour so that also replies from normal MUA are moved to the
>Chats-folder.
>
>NB: The messages are moved only when they're _viewed_ in Delta Chat. Up
>to this moment, they stay in the inbox. This is a desired behaviour to
>not miss some messages when switching from Delta Chat to a normal MUA
>for a given moment.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-core/issues/43#issuecomment-328931545

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gitkald** [comment] 2017-09-14 08:01
> NB: The messages are moved only when they're viewed in Delta Chat. Up to this moment, they stay in the inbox. This is a desired behaviour to not miss some messages when switching from Delta Chat to a normal MUA for a given moment.

Comes this with the next Release? At the moment this didn't worked with my account. All messages, described in the picture, still exists in "Inbox".  Whether read or not.

**Comment by r10s** [comment] 2017-09-14 15:43
Yes, this comes with 0.9.5 and should work on most systems (one system that is known not to work with the Chats folder is Google).

**Comment by gitkald** [comment] 2017-10-13 10:07
Sorry, the fix didn't worked on my devices.

In the logfile I found:
```
T2:Markin Message INBOX/361 as seen...
T2:$MDNSend just set and MDN will be send.
T2:Moving message INBOX/362 to Chats...
T2:Cannot move message
```

**Comment by r10s** [comment] 2017-10-13 11:44
Okay, for you it is still the case _no_ messages at all are moved to the `Chats` folder?

**Comment by r10s** [comment] 2017-10-13 11:48
I think we should refer to https://github.com/deltachat/deltachat-android/issues/108 then to keep things more concentrated.
(seems to be more  a problem with the folder usage for some providers, the code itself says, messages should be moved and so ...)

**Comment by gitkald** [comment] 2017-10-13 11:49
Correct. Same like described above.
If you will test it, I can create a mailbox for you on my domain for testing it.

**Comment by r10s** [comment] 2017-10-13 11:50
I do not find the time today or the next, but I would be glad if I can ask you as soon as I handle this issue.
